### ISSUE TITLE
Comparison?

### ISSUE THREAD

**Issue by Kevinco1** [vova7878-modules/NoStorageRestrict#1]
This is similar to Lucky Patcher as you have mentioned but what about Core Patch? Can I run both or is that not recommended.

**Comment by Kevinco1** [comment]
Sorry this was supposed to be posted in the repo for PMPatch. Can you move it there? Thanks

**Comment by vova7878** [comment]
> Can you move it there?

Нет, github не продоставляет такой возможности

> This is similar to Lucky Patcher as you have mentioned

Я давал эту информацию только на русском, так что будем считать, что вы его понимаете

> what about Core Patch?

Задача у модулей примерно одинаковая, но CorePatch менее структурирован - это просто сборник кучи разных вариантов как отключить проверку подписи. Что-то он делает больше, что-то меньше, но итог должен быть один

> Can I run both or is that not recommended.

Да, вы можете установить оба, но зачем? Они не должны конфликтовать, но я не отвечаю за итог, если это будет сделано

Надеюсь я ответил на ваш вопрос, спасибо
